{
    "notice": {
        "title": "お知らせ",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "time_stamp": {
                "label": "日時",
                "type": "datetime",
                "required": true
            },
            "message": {
                "label": "本文",
                "type": "textarea",
                "rows": 4,
                "required": true
            },
            "picture": {
                "label": "画像・動画URL",
                "type": "url",
                "required": false
            }
        }
    },
    "visual": {
        "title": "立ち絵",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "id": {
                "label": "管理番号",
                "type": "number",
                "required": true
            },
            "costume_name": {
                "label": "イラスト名(管理用)",
                "type": "text",
                "required": false
            },
            "visual_url": {
                "label": "立ち絵画像URL",
                "type": "url",
                "required": true
            },
            "thumb_url": {
                "label": "アイコン画像URL",
                "type": "url",
                "required": true
            },
            "thumb_background": {
                "label": "アイコン背景画像URL",
                "type": "url",
                "required": true
            },
            "comment": {
                "label": "立ち絵説明(管理用)",
                "type": "text",
                "required": false
            },
            "character_design": {
                "label": "キャラクター案",
                "type": "text",
                "required": false
            },
            "illustrator": {
                "label": "イラストレーター",
                "type": "text",
                "required": false
            },
            "2d_animation": {
                "label": "2Dデザイナー",
                "type": "text",
                "required": false
            },
            "3d_modeling": {
                "label": "3Dモデリング",
                "type": "text",
                "required": false
            },
            "priority": {
                "label": "表示順（優先度）",
                "type": "number",
                "min": 1,
                "required": true
            }
        }
    },
    "movies_priority": {
        "title": "動画カテゴリ",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "type": {
                "label": "動画カテゴリ",
                "type": "text",
                "required": true
            },
            "priority": {
                "label": "表示順（優先度）",
                "type": "number",
                "min": 1,
                "required": true
            }
        }
    },
    "movies": {
        "title": "動画",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "type": {
                "label": "動画カテゴリ",
                "type": "text",
                "required": true
            },
            "title": {
                "label": "動画タイトル",
                "type": "relation_select",
                "fromSheet": "movies_priority",
                "fromColumn": "type",
                "required": true
            },
            "image_url": {
                "label": "サムネイル画像URL",
                "type": "url",
                "required": false
            },
            "video_url": {
                "label": "動画URL",
                "type": "url",
                "required": true
            },
            "is_active": {
                "label": "公開設定",
                "type": "select",
                "options": ["true", "false"],
                "optionLabels": ["公開", "非公開"],
                "required": true
            }
        }
    },
    "shop": {
        "title": "ショップ",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "id": {
                "label": "管理番号",
                "type": "number",
                "required": true
            },
            "name": {
                "label": "商品名",
                "type": "text",
                "required": true
            },
            "merchandise_image": {
                "label": "商品画像URL",
                "type": "url",
                "required": true
            },
            "price": {
                "label": "価格（円）",
                "type": "number",
                "required": true
            },
            "booth": {
                "label": "BOOTH",
                "type": "url",
                "required": false
            },
            "suzuri": {
                "label": "SUZURI",
                "type": "url",
                "required": false
            },
            "base": {
                "label": "BASE",
                "type": "url",
                "required": false
            },
            "fanbox": {
                "label": "FANBOX",
                "type": "url",
                "required": false
            }
        }
    },
    "about": {
        "title": "その他",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "title": {
                "label": "タイトル",
                "type": "text",
                "required": true
            },
            "line": {
                "label": "表示ライン",
                "type": "number",
                "min": 1,
                "required": true
            },
            "type": {
                "label": "表示種類",
                "type": "select",
                "options": [ "ボタンリンク", "ストア", "メール", "テキスト" ],
                "required": true
            },
            "button_image": {
                "label": "ボタン画像URL",
                "type": "url",
                "required": true
            },
            "value": {
                "label": "設定値",
                "type": "text",
                "required": true
            },
            "title_value": {
                "label": "メール件名",
                "type": "text",
                "required": false
            },
            "text_value": {
                "label": "メール本文",
                "type": "textarea",
                "rows": 6,
                "required": false
            },
            "priority": {
                "label": "表示順（優先度）",
                "type": "number",
                "min": 1,
                "required": true
            }
        }
    },
    "guideline": {
        "title": "その他",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "text_value": {
                "label": "テキストタイプ",
                "type": "select",
                "options": [ "タイトル", "項目", "テキスト", "段落テキスト", "注釈" ],
                "required": true
            },
            "paragraph_group": {
                "label": "段落グループ",
                "type": "number",
                "min": 1,
                "required": false
            },
            "is_active": {
                "label": "太字可否",
                "type": "select",
                "options": ["true", "false"],
                "optionLabels": ["太字", "通常"],
                "required": true
            },
            "text": {
                "label": "テキスト",
                "type": "text",
                "required": false
            },
            "priority": {
                "label": "表示順（優先度）",
                "type": "number",
                "min": 1,
                "required": true
            }
        }
    },
    "profile": {
        "title": "基本プロフィール",
        "layout": "key-value",
        "dataStartRow": 1,
        "keyColumn": 1,
        "valueColumn": 2,
        "descColumn": 3,
        "items": {
            "name": {
                "label": "キャラクター名",
                "type": "text",
                "required": true
            },
            "pronunciation": {
                "label": "ふりがな",
                "type": "text",
                "required": true
            },
            "romanization": {
                "label": "ローマ字",
                "type": "text",
                "required": true
            },
            "birthday": {
                "label": "誕生日",
                "type": "date",
                "format": "MM月DD日",
                "required": false
            },
            "streaming": {
                "label": "配信活動開始日",
                "type": "date",
                "format": "YYYY年MM月DD日",
                "required": false
            },
            "age": {
                "label": "年齢",
                "type": "number",
                "min": 0,
                "required": false
            },
            "height": {
                "label": "身長(cm)",
                "type": "number",
                "required": false
            },
            "fan_name": {
                "label": "ファンネーム",
                "type": "text",
                "required": false
            },
            "comment": {
                "label": "キャッチフレーズ",
                "type": "text",
                "required": false
            },
            "message": {
                "label": "自己紹介メッセージ",
                "type": "textarea",
                "rows": 3,
                "required": false
            },
            "youtube_url": {
                "label": "YouTubeチャンネルURL",
                "type": "web",
                "required": false
            },
            "x_url": {
                "label": "X (旧Twitter) URL",
                "type": "web",
                "required": false
            },
            "sns_url-1": {
                "label": "配信プラットフォーム-1",
                "type": "web",
                "required": false
            },
            "sns_url-2": {
                "label": "配信プラットフォーム-2",
                "type": "web",
                "required": false
            },
            "sns_url-3": {
                "label": "配信プラットフォーム-3",
                "type": "web",
                "required": false
            },
            "movie_url-1": {
                "label": "自己紹介動画URL-1",
                "type": "web",
                "required": false
            },
            "movie_url-2": {
                "label": "自己紹介動画URL-2",
                "type": "web",
                "required": false
            },
            "movie_url-3": {
                "label": "自己紹介動画URL-3",
                "type": "web",
                "required": false
            }
        }
    },
    "account": {
        "title": "管理アカウント",
        "headerRow": 1,
        "dataStartRow": 2,
        "columns": {
            "account": {
                "label": "アカウント",
                "type": "text",
                "required": true
            },
            "password": {
                "label": "パスワード",
                "type": "text",
                "required": true
            },
            "authority": {
                "label": "権限",
                "type": "text",
                "required": true
            }
        }
    }
}
